<?php

namespace app\test\controller;

use think\Controller;
use app\model\User as UserModel;
class See extends Controller
{   //视图过滤：类全局
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
//        $this->filter(function ($content){
//            return str_replace('1','<br>',$content);
//        });
    }


    public function index(){
        //自动定位
//        return $this->fetch();
        //其他页面，例如edit
//        return $this->fetch('edit');
//        return $this->fetch('admin');
//        $this->assign('name','Mr.Lee');
//        $this->assign([
//            'name'              =>          '辉夜',
//            'gender'            =>          '女',
//            'email'             =>          'huiye@163.com',
//        ]);
//        return $this->fetch('index');
//        return $this->fetch('index',[
//            'name'              =>          '辉夜',
//            'gender'            =>          '女',
//            'email'             =>          'huiye@163.com',
//        ]);
        //助手函数
//        return view('index',[
//            'name'          =>          '辉夜',
//            'gender'            =>          '女',
//            'email'             =>          'huiye@163.com',
//        ]);
        //视图过滤:局部
//        $this->filter(function ($content){
//            return str_replace('1','<br>',$content);
//        });
        return view('index')->assign([
            'name'              =>          '辉1夜',
            'gender'            =>          '女',
            'email'             =>          'huiye@163.com',
        ]);


    }
    public function testDisplay(){
        $content = '{$username}.{$gender}.{$email}';
         return $this->display($content,[
            'username'          =>          '辉1夜',
            'gender'            =>          '女',
            'email'             =>          'huiye@163.com',
        ]);
    }

    public function varOutput(){
        $this->assign('name','ThinkPHP');
        $data['username'] = '辉夜';
        $data['email'] = 'huiye@163.com';
        $this->assign('user',$data);

        $obj = new \stdClass();
        $obj-> username = '辉夜';
        $obj->email = 'huiye@163.com';
        $this->assign('obj',$obj);

        $this->assign('password','123456');
        $this->assign('time',time());
        $this->assign('number',10);
        return $this->fetch('var');
    }
    public function loop(){
        $list = UserModel::all();
        $this->assign('list',$list);
        return $this->fetch('loop');
    }
}